---
title: "week4"
author: "Faith"
format: html
editor: visual
---

## week 4

```{r}
library(tidyverse)
library(here)
library(janitor)
library(plotly)
library(rnaturalearth)
library(leaflet)
library(sf)
library(vembedr)
library(ggpubr)
library(ggcorrplot)
library(naniar)
library(missRanger)
```

```{r}
sdr_data <- read_csv(here("data/SDR-2023-Data.csv"))
```

```{r}
sdr_data <- sdr_data %>% 
  clean_names()
```

```{r}
sdr_data_normalized_scores <- sdr_data %>% 
  select(country, contains("normalized_score"))

```

```{r}
gg_miss_var(sdr_data_normalized_scores, show_pct = TRUE) +
  theme(axis.text.y = element_text(size = 8)) 
```

```{r}
sdr_data_normalized_scores_longer <- sdr_data_normalized_scores %>% 
  pivot_longer(cols = !country)
```

```{r}
missing_data_by_country <- sdr_data_normalized_scores_longer %>%
 group_by(country) %>%
 miss_var_summary() %>% 
 arrange(desc(pct_miss))

missing_data_by_country
```

```{r}
completely_na_countries  <- missing_data_by_country$country[missing_data_by_country$pct_miss == 100]
completely_na_countries
```

```{r}
sdr_data_normalized_scores_no_na_countries <- sdr_data_normalized_scores %>% 
  filter(!country %in% completely_na_countries)
```

```{r}
gg_miss_var(sdr_data_normalized_scores_no_na_countries, show_pct = TRUE) +
  theme(axis.text.y = element_text(size = 8)) +
  geom_hline(yintercept = 20, color = "steelblue", linetype = "dashed")
```

```{r}
sdr_data_normalized_scores_less_na <- sdr_data_normalized_scores_no_na_countries %>%
  select(where(~ sum(is.na(.))/length(.) <= 0.2))
```

```{r}
sdr_data_imputed <- missRanger(sdr_data_normalized_scores_less_na)
```

```{r}
sdr_data_imputed <- sdr_data_imputed %>%
  remove_rownames %>%
  column_to_rownames(var="country")
```

```{r}

```

```{r}

```

```{r}

```
